version: "3"

services:
  redis:
    image: redis
    command: "redis-server --requirepass foobared"
    restart: always
    ports:
      - 6379:6379
    env_file:
      - ./redis/.env
    volumes:
      - ./redis:/data
    networks:
      - backend
  telegram_bot:
    build: telegram_bot
    volumes:
      - './telegram_bot:/app/telegram_bot/'
    restart: "always"
    env_file:
      - ./telegram_bot/.env
    ports:
      - "${TGBOT_EXTERNAL_PORT}:8080"
    depends_on:
      - database
      - redis
      - core
    networks:
      - backend
  database:
    image: postgis/postgis
    restart: always
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - backend
  core:
      build: core
      command: sh -c "python manage.py migrate && python manage.py collectstatic
        --no-input && sh ./bin/start_gunicorn.sh"
      restart: always
      volumes:
        - ./core:/app/core/
      env_file:
        - ./core/.env
      ports:
        - "8001:8001"
      networks:
        - backend
      depends_on:
        - database


networks:
  backend:
    driver: bridge
