version: "3"

services:

  redis:
    image: redis
    command: "redis-server --requirepass foobared"
    restart: always
    env_file:
      - ./redis/.env
    volumes:
      - ./redis:/data
    networks:
      - backend


  telegram_bot:
    build: telegram_bot
    volumes:
      - './telegram_bot:/app/telegram_bot/'
    restart: "always"
    env_file:
      - ./telegram_bot/.env
    ports:
      - "${TGBOT_EXTERNAL_PORT}:80"
    depends_on:
      - redis
    networks:
      - backend
      

networks:
  backend:
    driver: bridge
